### ISSUE TITLE
strange glitch

### ISSUE THREAD

**Issue by Ace-Stargale** [TohnoCoding/fgochecklist#9] opened 2024-09-11 14:53 UTC
I've been using this list for a while to keep track of who I have and NP levels, and it's really good- except a few days ago it stopped  letting me update NP levels entirely. I have to use Safari as my browser, so I don't know if that has something to do with it, but it's just flat-out not letting me update NP levels. When I click save changes, nothing happens, the update box doesn't even disappear. It's like the save changes button is entirely unresponsive. Everything else still works, including fast mode, it's just the manual update save changes button that's broken.

**Comment by TohnoCoding** [comment] 2024-09-11 15:54
@Ace-Stargale can you give me more details?
- Platform (iOS, Android, MacOS, Windows, *nix)
- Browser version
- Maybe a screen recording?
That way I can better figure out what's going on.

**Comment by Ace-Stargale** [comment] 2024-09-11 15:59
I'm on MacOS Sonoma 14.6.1, Safari Version 17.6 (19618.3.11.11.5).
For some reason I can't take a screen recording that fits the upload size, sorry. Literally everything is working except for the save changes button.

**Comment by Ace-Stargale** [comment] 2024-09-11 16:02
https://github.com/user-attachments/assets/e67ac275-692d-481c-ae6d-4859853a1920

**Comment by TohnoCoding** [comment] 2024-09-11 16:37
Thank you for the screen recording; since I generally use the list myself in Fast Mode, I wouldn't have caught that. I forgot to change the name of a function being called in the HTML when I renamed the function in the JS code for better readability. The issue is fixed now. :)

**Closed by TohnoCoding** 2024-09-11 16:37 UTC
